version: "3.5"

services:
  app:
    container_name: cookbook_app
    image: cookbook
    build: ./
    ports:
      - "8080:8080"
    env_file: ./.env
    environment:
      DATASOURCE_URL: ${URL}
      DATASOURCE_USERNAME: ${USER}
      DATASOURCE_PASSWORD: ${PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    container_name: cookbook_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cookbook
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: ./.env

volumes:
  postgres-data: