version: "3.5"

services:
  app:
    container_name: cookbook_app
    image: cookbook
    build: ./
    ports:
      - "8080:8080"
    env_file: ./.env
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/cookbook
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: root
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    container_name: cookbook_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cookbook
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_URL=jdbc:postgresql://localhost:5432/cookbook
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: ./.env

volumes:
  postgres-data: